package io.btc.supercr.db

import codereview.FileLineItem
import codereview.FileType
import codereview.ReviewInfo
import codereview.ReviewStorageProvider
import git.provider.PullRequestSummary
import kotlinx.serialization.Serializable


fun PullRequestSummary.toReviewInfo(projectIdentifier: String): ReviewInfo {
    return ReviewInfo(
        rowId = null,
        projectIdentifier = projectIdentifier,
        provider = ReviewStorageProvider.GITHUB,
        providerId = this.number.toLong()
    )
}

@Serializable
data class FileReviewInfo(
    /** Generated By DB */
    val rowId: Long?,
    val path: String,
    val reviewId: Long,
    val fileType: FileType
)

@Serializable
data class FileLineComment(
    /** Generated by DB */
    val fileReviewId: Long?,
    val rowNumber: Long,
    val body: String,
    val createdAt: String,
    val updatedAt: String,
    val userId: String
)

fun FileLineComment.toLineComment(): FileLineItem.Comment {
    return FileLineItem.Comment(body, createdAt, updatedAt, userId)
}

fun FileLineItem.Comment.toFileLineComment(rowNumber: Long) : FileLineComment {
    return FileLineComment(null, rowNumber, body, createdAt, updatedAt, userId)
}