package codereview

import kotlinx.serialization.Serializable


@Serializable
data class Project(
    val localPath: String,
    val providerPath: String,
    val name: String
) {
    /** TODO : Get encodeToBase64 to work */
//    val id = localPath.encodeToBase64()
    val id
    get() = localPath.replace("/", "")
}
@Serializable
data class ReviewInfo(
    /** Generated by DB */
    val rowId: Long?,
    val projectIdentifier: String,
    val provider: ReviewStorageProvider,
    val providerId: Long
)

@Serializable
enum class ReviewStorageProvider{
    GITHUB
}

@Serializable
enum class FileType{
    OLD_FILE,
    NEW_FILE
}

